// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gofiber/fiber/v3"
	"go-fiber-ent-web-layout/internal/conf"
)

// Injectors from wire.go:

// wireApp generate inject code
func wireApp(contextContext context.Context, data *conf.Data, jwt *conf.Jwt, server *conf.Server) (*fiber.App, func(), error) {
	app := newApp(contextContext, server)
	return app, func() {
	}, nil
}
